config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'setup/index'

  get 'personnels/personnel_index'
  get 'personnels/personnel_new'
  post 'personnels/personnel_create'
  get 'personnels/personnel_edit'
  post 'personnels/personnel_update'
  get 'personnels/personnel_destroy'

  get 'personnels/item_index'
  get 'personnels/item_new'
  post 'personnels/item_create'
  get 'personnels/item_edit'
  post 'personnels/item_update'
  get 'personnels/item_destroy'


  get 'current_user' => "personnels#current_user"
  get "sessions/new"

  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'personnels#new'
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/personnel.rb
class Personnel < ApplicationRecord


	has_secure_password

# 	def self.authenticate(email, password)
  #   personnel = find_by(email: email)
  #   if personnel && personnel.password_digest == BCrypt::Engine.hash_secret(password, personnel.password_salt)
  #     personnel
  #   else
  #     nil
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
	helper_method :current_personnel

	def current_personnel
	  @current_personnel ||= Personnel.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token]
	end
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController

skip_before_action :verify_authenticity_token, only: [ :item_create, :personnel_create]


	def personnel_index
		@personnels = Personnel.all
	end

	def personnel_new
	end

	def personnel_create
		personnel = Personnel.new
		personnel.name = params[:name]
		personnel.email = params[:email]
		personnel.password = params[:password]
		personnel.password_digest = params[:password_digest]
		personnel.save

		flash[:success] = "Personnel Created Successfully."
		redirect_to personnels_personnel_index_url
	end

	def personnel_edit
		@personnel = Personnel.find(params[:format])
	end

	def personnel_update
		personnel = Personnel.find(params[:personnel_id])
		personnel.update(name: params[:name],email: params[:email])
		flash[:success] = "Personnel Update Successfully."
		redirect_to personnels_personnel_index_url
	end
	def personnel_destroy 
		@personnel = Personnel.find(params[:format])
		@personnel.destroy

		flash[:success] = "Personnel Destroy Successfully."
		redirect_to personnels_personnel_index_url
	end

	def item_index
		@items = Item.all
	end

	def item_new
	end

	def item_create
		item = Item.new
		item.name = params[:name]
		item.save

		flash[:success] = "Item Created Successfully."
		redirect_to personnels_item_index_url
	end

	def item_edit
		@item = Item.find(params[:format])
	end

	def item_update
		item = Item.find(params[:item_id])
		item.update(name: params[:name])

		flash[:success] = "Item update Successfully"
		redirect_to personnels_item_index_url
	end

	def item_destroy
		@item = Item.find(params[:format])
		@item.destroy

		flash[:success] = "Item Delete Successfully"
		redirect_to personnels_item_index_url
	end






	private
    def set_personnel
      @personnel = Personnel.find(params[:id])
    end

   def personnel_params
      params.require(:personnel).permit(:email, :name, :auth_token, :password, :password_confirmation)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@original_url=params[:original_url]
	end

	def create
	  personnel = Personnel.find_by(email: params[:login][:email].downcase)
	  if personnel && personnel.authenticate(params[:login][:password])
	    session[:personnel_id] = personnel.id.to_s
	    # Redirect to the desired path after successful login
	    redirect_to your_desired_path, notice: 'Successfully logged in!'
	  else
	    flash.now[:alert] = 'Invalid email or password'
	    render 'new'
	  end
	end

	# def create
	#   if params[:login].present?
	#     personnel = Personnel.find_by(email: params[:login][:email].downcase)
	#     if personnel && personnel.authenticate(params[:login][:password])
	#       session[:personnel_id] = personnel.id.to_s
	#       # Redirect to the desired path after successful login
	#       redirect_to your_desired_path, notice: 'Successfully logged in!'

	#     else
	#       flash.now[:alert] = 'Invalid email or password'
	#       render 'new'
	#     end
	#   else
	#     # Handle the case where login params are missing
	#      # flash.now[:alert] = 'Invalid email or password'
	#      render 'new'
	#   end
	# end

end

app/controllers/setup_controller.rb
class SetupController < ApplicationController

	def index
	end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/setup_helper.rb
module SetupHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyCost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if notice %>
      <%= notice %>
  <% end %>
  
  <% if alert %>
      <%= alert %>
  <% end %>



    <%= yield %>
  </body>
</html>

app/views/personnels/item_edit.html.erb
<%= form_tag 'item_update' do %>
 <%= hidden_field_tag "item_id", @item.id %>

 <h1>Edit Item</h1>
	<label>Name:</label><%= text_field_tag "name", @item.name %><br>
	<br>
	<%= submit_tag 'Update Item' %>
<%end%>	

app/views/personnels/item_index.html.erb
<h1>Item Index</h1>
<%= link_to 'New Item', personnels_item_new_url %>
<table>
  <thead>
      <th>Name</th>
      <th></th>
      <th></th>
  </thead>
  <tbody>
  	<% @items.each do |item| %>
  	<tr>
  		<td><%= item.name %></td>
  		<td><%= link_to 'Edit', personnels_item_edit_path(item) %></td>
  		<td><%= link_to 'Destroy', personnels_item_destroy_path(item) %></td>
  	</tr>
  	<%end%>

  </tbody>
</table>

app/views/personnels/item_new.html.erb
<%= form_tag 'item_create' do %>

 <h1>Generate Item</h1>
	<label>Name:</label><%= text_field_tag "name"," " %><br>
	<br>
	<%= submit_tag 'Create Item' %>
<%end%>	

app/views/personnels/personnel_edit.html.erb
<%= form_tag 'personnel_update' do %>
 <%= hidden_field_tag "personnel_id", @personnel.id %>

 <h1>Edit Personnel</h1>
	<label>Name:</label><%= text_field_tag "name", @personnel.name %><br>
	<br>
	<label>Email:</label><%= text_field_tag "email", @personnel.email  %><br>
	<br>
	<%= submit_tag 'Update Personnel' %>
<%end%>	

app/views/personnels/personnel_index.html.erb
<h1>Personnel Index</h1>
<%= link_to 'New Personnel', personnels_personnel_new_url %>
<table>
  <thead>
      <th>Name</th>
      <th>Email</th>
      
      <th></th>
      <th></th>
  </thead>
  <tbody>
  	<% @personnels.each do |personnel| %>
  	<tr>
  		<td><%= personnel.name %></td>
  		<td><%= personnel.email %></td>
  		
  		<td><%= link_to 'Edit', personnels_personnel_edit_path(personnel) %></td>
  		<td><%= link_to 'Destroy', personnels_personnel_destroy_path(personnel) %></td>
  	</tr>
  	<%end%>

  </tbody>
</table>

app/views/personnels/personnel_new.html.erb
<%= form_tag 'personnel_create' do %>

 <h1>Generate Personnel</h1>
	<label>Name:</label><%= text_field_tag "name"," " %><br>
	<br>
	<label>Email:</label><%= text_field_tag "email"," " %><br>
	<br>
	<label>Password:</label><%= text_field_tag "password", " " %><br>
	<br>
	<label>Password Confirmation:</label><%= text_field_tag "password_digest", " " %><br>
	<br>
	<%= submit_tag 'Create Personnel' %>
<%end%>	

app/views/setup/index.html.erb
<h1>Setup Index</h1>
<ul><%= link_to 'Personnel', personnels_personnel_index_url %></ul>
<ul><%= link_to 'Item', personnels_item_index_url %></ul>